package classes

//Has this code generated by default
/**
 * copy()
 * toString()
 * componentN()
 * equals()
 * hashcode()
 *
 * */

data class PetData(val name: String, val animalType: String )


data class PersonData(
    val name:String,
    val  lastName:String,
    val age: Int,
    val pet:PetData
)




fun main(){

    val dog = PetData("Max", "Mini Dacshund")
    val jamie = PersonData("Jamie", "Mason-Wright", 35, dog)
    println(jamie)

    val olderJamie = jamie.copy(age = jamie.age + 20)
    println(olderJamie)

    val(name, _,age  , pet) = olderJamie
    println("$age $pet")

    val firstName = olderJamie.component1()
    println(firstName)


    var jamieTwo = jamie
    println(jamieTwo == jamie)
    println(jamieTwo === jamie)

    jamieTwo = jamie.copy()
    println(jamieTwo == jamie)
    println(jamieTwo === jamie)

}